services:
  butterfly-db:
    container_name: butterfly-db
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: butterfly
      POSTGRES_USER: chimbori
      POSTGRES_PASSWORD: chimbori
    ports:
      - 5432:5432
    volumes:
      - /Users/Shared/Unsynced/butterfly-db-data:/var/lib/postgresql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/butterfly", "--config=/data/butterfly.yml", "--healthcheck"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  butterfly-db-data:
